"""

Revision ID: 3b52f0650d91
Revises: 0001
Create Date: 2026-07-06 23:41:24.314216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "3b52f0650d91"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
